In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Numpy

In [206]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

In [ ]:
np.__version__

Matrix 2D Areay

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[0]
a[2:5]

In [ ]:
L = [1,2,3,4,5,6,7]
L[0]
L[2:5]

In [ ]:
a[:6]

In [ ]:
L[:6]

In [ ]:
a[3:]

In [ ]:
L[3:]

-1 จากท้ายสุด 1ตัว

In [ ]:
a[-1]

In [ ]:
a[1:-3]

In [ ]:
a[-2:2]

In [ ]:
np.size(a)

เวกเตอร์

In [ ]:
np.shape(a)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a[2]]

นับตำแหน่งaเป็น 0 1 2

In [ ]:
a[1]

a array.reverse ไม่ได้

In [ ]:
L = [1,2,3,4,5,6,7]
L.reverse()
L

sorted

In [ ]:
sorted(a, reverse=True)

In [ ]:
a = a.reshape(1,10)
np.shape(a)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

if L[0][0]

In [ ]:
a[0,0]

In [ ]:
a[:,0]

In [ ]:
a[:,1] = 0
a

In [ ]:
a[1,:] = 0
a

In [ ]:
a[0:2 , :] = 8
a

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
np.size(a,1)

ข้อมูลมี2dimansion

In [ ]:
np.ndim(a)

**Data is Matrix.**
So, Matrix management == Data Management
rows = samples
columns = attributes, features

In [ ]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

**dtype = int)******

In [ ]:
np.array(np_mix_matrix[:,1], dtype = int)

In [ ]:
a = np.zeros((5,3))
a

**Special Type of Matrix**

In [ ]:
a = np.ones((5,3))
a

In [ ]:
c = np.full((5,5),8)
c

In [ ]:
d = np.eye(5,5)
d

In [ ]:
c*d

**matrix c*d**

In [ ]:
np.matmul(c,d)

**Random**

In [ ]:
np.random.rand()

In [ ]:
np.random.rand()*10

In [ ]:
np.random.randint(5)

In [ ]:
rng = np.random.seed(0)
[np.random.rand(5) for item in range(10)]

**เพื่อให้ไม่ซ้ำกัน replace=False)**

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

In [ ]:
np_matrix = np.round(np.random.rand(1000,5))
np_matrix

สุ่มข้อมูล จาก1000 มา 100

In [ ]:
rng = np.random.seed(0)
idx_choose = np.random.choice(1000,100, replace = False)
idx_choose

In [ ]:
np_matrix_choose = np_matrix[idx_choose]
np_matrix

# Ex.2

* Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.




In [213]:
np_matrix = np.random.rand(10,5)
np_matrix[:, -1] = np.round(np_matrix[:, -1])
np_matrix

array([[0.67781654, 0.27000797, 0.73519402, 0.96218855, 0.        ],
       [0.57615733, 0.59204193, 0.57225191, 0.22308163, 1.        ],
       [0.44712538, 0.84640867, 0.69947928, 0.29743695, 1.        ],
       [0.39650574, 0.8811032 , 0.58127287, 0.88173536, 1.        ],
       [0.72525428, 0.50132438, 0.95608363, 0.6439902 , 0.        ],
       [0.60639321, 0.0191932 , 0.30157482, 0.66017354, 0.        ],
       [0.61801543, 0.4287687 , 0.13547406, 0.29828233, 1.        ],
       [0.59087276, 0.57432525, 0.65320082, 0.65210327, 0.        ],
       [0.8965466 , 0.36756187, 0.43586493, 0.89192336, 1.        ],
       [0.70388858, 0.10022689, 0.91948261, 0.7142413 , 1.        ]])

In [215]:
rng = np.random.seed(0)
[np.random.rand(5) for item in range(10)]


[array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ]),
 array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152]),
 array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]),
 array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215]),
 array([0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443]),
 array([0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194]),
 array([0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ]),
 array([0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ]),
 array([0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672]),
 array([0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077])]

In [216]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 9, 10,  4,  4,  6],
       [ 4,  4,  3,  4,  4],
       [ 8,  4,  3, 10,  7],
       [ 5,  5,  0,  1,  5],
       [ 9,  3,  0,  5,  0]])

In [218]:
row,colum = np.where(np_matrix == 2)
[(row[i],colum[i]) for i in range(len(row))]

[]

# Ex.3

* Why we cannot use this index ? Please fix it !!
* idx = [1,2,3,4,5]
* np_matrix[idx,:]

In [237]:
np_matrix = np.random.randint(5,size = (5,5))
np_matrix

array([[3, 0, 4, 4, 0],
       [1, 3, 4, 3, 2],
       [1, 1, 2, 1, 4],
       [2, 4, 4, 2, 3],
       [3, 1, 2, 4, 3]])

In [238]:
new_idx = [1,2,3,4,5]
np_matrix[new_idx,:]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [245]:
idx = [1,2,3]
np_matrix[idx,:]

idx = [1,2,3,4]
np_matrix[idx,:]

idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]

#idxนับค่าในช่วง 1-5 มี5ตัว แต่ np_matrix นับตั้งแต่ 0 ไม่เอา 5 จึงเกิด Error วิธีแก้คือ ใส่ len(idx)-1
#IndexError: index 5 is out of bounds for axis 0 with size 5

array([3, 1, 2, 4, 3])

In [ ]:
np_matrix = np.random.randint(3,size = (5,6))
np_matrix

In [ ]:
rng = np.random.RandomState(0)
rng.randint(5)

In [ ]:
rng = np.random.RandomState(0) 
np_matrix = rng.randomint

In [ ]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

In [ ]:
a = np_matrix ==2
a


In [ ]:
np_matrix[a] =99
np_matrix

In [ ]:
np_matrix[a == 2] = 99
np_matrix

# Ex.4

* Randomly create a data matrix of 10 samples with 5 features. 
*  Then, randomly create a label vector for 10 samples. 
*  Finally, seperate samples into 2 groups
*  Group 1 called train_data (label == 0)
*  Group 2 called test_data (label == 1)

In [246]:
np_matrix = np.random.randint(10,size = (10,5))
np_matrix

array([[3, 1, 9, 5, 9],
       [9, 2, 0, 9, 1],
       [9, 0, 6, 0, 4],
       [8, 4, 3, 3, 8],
       [8, 7, 0, 3, 8],
       [7, 7, 1, 8, 4],
       [7, 0, 4, 9, 0],
       [6, 4, 2, 4, 6],
       [3, 3, 7, 8, 5],
       [0, 8, 5, 4, 7]])

In [247]:
#create vactor
vector = np.random.randint(2,size=10) 
vector

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 1])

In [248]:
#Group 1 called train_data (label == 0)
np_matrix[np.where(label_vector == 0)]

array([[3, 1, 9, 5, 9],
       [9, 2, 0, 9, 1],
       [7, 7, 1, 8, 4],
       [3, 3, 7, 8, 5]])

In [249]:
#Group 2 called test_data (label == 1)
np_matrix[np.where(label_vector == 1)]

array([[9, 0, 6, 0, 4],
       [8, 4, 3, 3, 8],
       [8, 7, 0, 3, 8],
       [7, 0, 4, 9, 0],
       [6, 4, 2, 4, 6],
       [0, 8, 5, 4, 7]])