In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Numpy

In [266]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

In [ ]:
np.__version__

Matrix 2D Areay

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[0]
a[2:5]

In [ ]:
L = [1,2,3,4,5,6,7]
L[0]
L[2:5]

In [ ]:
a[:6]

In [ ]:
L[:6]

In [ ]:
a[3:]

In [ ]:
L[3:]

-1 จากท้ายสุด 1ตัว

In [ ]:
a[-1]

In [ ]:
a[1:-3]

In [ ]:
a[-2:2]

In [ ]:
np.size(a)

เวกเตอร์

In [ ]:
np.shape(a)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a[2]]

นับตำแหน่งaเป็น 0 1 2

In [ ]:
a[1]

a array.reverse ไม่ได้

In [ ]:
L = [1,2,3,4,5,6,7]
L.reverse()
L

sorted

In [ ]:
sorted(a, reverse=True)

In [ ]:
a = a.reshape(1,10)
np.shape(a)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

if L[0][0]

In [ ]:
a[0,0]

In [ ]:
a[:,0]

In [ ]:
a[:,1] = 0
a

In [ ]:
a[1,:] = 0
a

In [ ]:
a[0:2 , :] = 8
a

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
np.size(a,1)

ข้อมูลมี2dimansion

In [ ]:
np.ndim(a)

**Data is Matrix.**
So, Matrix management == Data Management
rows = samples
columns = attributes, features

In [ ]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

**dtype = int)******

In [ ]:
np.array(np_mix_matrix[:,1], dtype = int)

In [ ]:
a = np.zeros((5,3))
a

**Special Type of Matrix**

In [ ]:
a = np.ones((5,3))
a

In [ ]:
c = np.full((5,5),8)
c

In [ ]:
d = np.eye(5,5)
d

In [ ]:
c*d

**matrix c*d**

In [ ]:
np.matmul(c,d)

**Random**

In [ ]:
np.random.rand()

In [ ]:
np.random.rand()*10

In [ ]:
np.random.randint(5)

In [ ]:
rng = np.random.seed(0)
[np.random.rand(5) for item in range(10)]

**เพื่อให้ไม่ซ้ำกัน replace=False)**

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

In [ ]:
np_matrix = np.round(np.random.rand(1000,5))
np_matrix

สุ่มข้อมูล จาก1000 มา 100

In [ ]:
rng = np.random.seed(0)
idx_choose = np.random.choice(1000,100, replace = False)
idx_choose

In [ ]:
np_matrix_choose = np_matrix[idx_choose]
np_matrix

# Ex.2

* Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.




In [267]:
np_matrix = np.random.rand(10,5)
np_matrix[:, -1] = np.round(np_matrix[:, -1])
np_matrix

array([[0.98432943, 0.70349478, 0.1816312 , 0.51239346, 1.        ],
       [0.78754216, 0.60647546, 0.21840285, 0.45516882, 1.        ],
       [0.49226824, 0.71556116, 0.48615956, 0.70854815, 0.        ],
       [0.84455008, 0.19434222, 0.77332601, 0.97425866, 1.        ],
       [0.78042665, 0.98503228, 0.75356961, 0.00404811, 0.        ],
       [0.41049214, 0.42822383, 0.29784182, 0.40113234, 0.        ],
       [0.98069967, 0.40612049, 0.56921076, 0.3436055 , 1.        ],
       [0.41137241, 0.35927142, 0.39949891, 0.30183088, 1.        ],
       [0.92621293, 0.32531031, 0.95287067, 0.0139484 , 1.        ],
       [0.30458203, 0.88286   , 0.25062272, 0.67741183, 1.        ]])

In [ ]:
rng = np.random.seed(0)
[np.random.rand(5) for item in range(10)]


In [ ]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

In [ ]:
row,colum = np.where(np_matrix == 2)
[(row[i],colum[i]) for i in range(len(row))]

# Ex.3

* Why we cannot use this index ? Please fix it !!
* idx = [1,2,3,4,5]
* np_matrix[idx,:]

In [274]:
np_matrix = np.random.randint(5,size = (5,5))
np_matrix

array([[4, 1, 4, 1, 4],
       [1, 2, 2, 3, 1],
       [2, 2, 4, 2, 2],
       [3, 0, 4, 2, 0],
       [0, 2, 3, 1, 3]])

In [275]:
idx = [1,2,3,4,5]
np_matrix[idx,:]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [276]:
idx = [1,2,3]
np_matrix[idx,:]

idx = [1,2,3,4]
np_matrix[idx,:]

#idxนับ 1-5 มี5ตัว แต่ np_matrix นับตั้งแต่ 0 ไม่เอา 5 มี 4ตัว จึงเกิด Error
#IndexError: index 5 is out of bounds for axis 0 with size 5

array([[1, 2, 2, 3, 1],
       [2, 2, 4, 2, 2],
       [3, 0, 4, 2, 0],
       [0, 2, 3, 1, 3]])

In [278]:
np_matrix[len(idx)-1,:]

array([3, 0, 4, 2, 0])

In [271]:
np_matrix = np.random.randint(3,size = (5,6))
np_matrix

array([[1, 2, 1, 1, 1, 0],
       [0, 2, 0, 0, 2, 1],
       [2, 2, 0, 2, 2, 0],
       [2, 1, 0, 1, 2, 1],
       [1, 0, 1, 1, 1, 2]])

In [ ]:
rng = np.random.RandomState(0)
rng.randint(5)

In [ ]:
rng = np.random.RandomState(0) 
np_matrix = rng.randomint

In [ ]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

In [ ]:
a = np_matrix ==2
a


In [ ]:
np_matrix[a] =99
np_matrix

In [ ]:
np_matrix[a == 2] = 99
np_matrix

# Ex.4

* Randomly create a data matrix of 10 samples with 5 features. 
*  Then, randomly create a label vector for 10 samples. 
*  Finally, seperate samples into 2 groups
*  Group 1 called train_data (label == 0)
*  Group 2 called test_data (label == 1)

In [279]:
np_matrix = np.random.randint(10,size = (10,5))
np_matrix

array([[2, 7, 1, 9, 2],
       [2, 5, 6, 4, 2],
       [2, 1, 0, 9, 0],
       [2, 8, 3, 0, 8],
       [8, 1, 0, 5, 8],
       [2, 3, 5, 3, 8],
       [6, 4, 6, 3, 6],
       [2, 6, 5, 5, 9],
       [4, 6, 5, 1, 3],
       [3, 8, 9, 5, 5]])

In [280]:
#create vactor
vector = np.random.randint(2,size=10) 
vector

array([0, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [283]:
#Group 1 called train_data (label == 0)
np_matrix[np.where(vector == 0)]

array([[2, 7, 1, 9, 2],
       [2, 5, 6, 4, 2],
       [2, 8, 3, 0, 8],
       [3, 8, 9, 5, 5]])

In [284]:
#Group 2 called test_data (label == 1)
np_matrix[np.where(vector == 1)]

array([[2, 1, 0, 9, 0],
       [8, 1, 0, 5, 8],
       [2, 3, 5, 3, 8],
       [6, 4, 6, 3, 6],
       [2, 6, 5, 5, 9],
       [4, 6, 5, 1, 3]])